"""empty message

Revision ID: 09e21e992631
Revises: b762f56a8109
Create Date: 2019-07-23 19:40:50.529077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09e21e992631'
down_revision = 'b762f56a8109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finded', sa.Column('findedPet', sa.String(length=80), nullable=False))
    op.drop_index('email', table_name='finded')
    op.drop_index('username', table_name='finded')
    op.drop_column('finded', 'email')
    op.drop_column('finded', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finded', sa.Column('username', mysql.VARCHAR(length=80), nullable=False))
    op.add_column('finded', sa.Column('email', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('username', 'finded', ['username'], unique=True)
    op.create_index('email', 'finded', ['email'], unique=True)
    op.drop_column('finded', 'findedPet')
    # ### end Alembic commands ###
