"""empty message

Revision ID: 2167f59d73d4
Revises: f7819058d5c3
Create Date: 2019-08-11 03:26:58.622875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2167f59d73d4'
down_revision = 'f7819058d5c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('breed', table_name='pets')
    op.drop_index('gender', table_name='pets')
    op.drop_index('name', table_name='pets')
    op.drop_index('size', table_name='pets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('size', 'pets', ['size'], unique=True)
    op.create_index('name', 'pets', ['name'], unique=True)
    op.create_index('gender', 'pets', ['gender'], unique=True)
    op.create_index('breed', 'pets', ['breed'], unique=True)
    # ### end Alembic commands ###
