"""empty message

Revision ID: 2ecdb3a86f2a
Revises: 730a34bab1e3
Create Date: 2019-08-09 15:53:59.637039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ecdb3a86f2a'
down_revision = '730a34bab1e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adverts', 'pet_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_index('pet_id', table_name='adverts')
    op.add_column('user', sa.Column('accountNumber', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('accountType', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('bank', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('rut', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'user', ['rut'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'rut')
    op.drop_column('user', 'bank')
    op.drop_column('user', 'accountType')
    op.drop_column('user', 'accountNumber')
    op.create_index('pet_id', 'adverts', ['pet_id'], unique=True)
    op.alter_column('adverts', 'pet_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
