"""empty message

Revision ID: 30753048b836
Revises: 2d07ec4cf94a
Create Date: 2019-08-03 15:02:31.177597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30753048b836'
down_revision = '2d07ec4cf94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adverts', 'address',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('adverts', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('adverts', 'description',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('adverts', 'status',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adverts', 'status',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('adverts', 'description',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('adverts', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('adverts', 'address',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###
