"""empty message

Revision ID: 6ce81be67cae
Revises: 09e21e992631
Create Date: 2019-08-02 01:11:12.770225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ce81be67cae'
down_revision = '09e21e992631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('breed', sa.String(length=80), nullable=True),
    sa.Column('gender', sa.String(length=80), nullable=True),
    sa.Column('size', sa.String(length=120), nullable=False),
    sa.Column('photo', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breed'),
    sa.UniqueConstraint('gender'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('size')
    )
    op.create_table('adverts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('finded')
    op.drop_table('lost')
    op.add_column('user', sa.Column('firstname', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('lastname', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'user', ['firstname'])
    op.create_unique_constraint(None, 'user', ['lastname'])
    op.drop_column('user', 'findings')
    op.drop_column('user', 'searchRequests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('searchRequests', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('findings', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    op.create_table('lost',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('petName', mysql.VARCHAR(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='lost_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('finded',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('findedPet', mysql.VARCHAR(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='finded_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('adverts')
    op.drop_table('pets')
    # ### end Alembic commands ###
