"""empty message

Revision ID: 90e5b517550a
Revises: af4097442f1a
Create Date: 2019-08-16 02:14:54.686869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90e5b517550a'
down_revision = 'af4097442f1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('photo_ibfk_1', 'photo', type_='foreignkey')
    op.drop_column('photo', 'pet_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('pet_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('photo_ibfk_1', 'photo', 'pets', ['pet_id'], ['id'])
    # ### end Alembic commands ###
