"""empty message

Revision ID: a02931ce6cdb
Revises: e3b5d47d655b
Create Date: 2019-08-07 21:01:23.811515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a02931ce6cdb'
down_revision = 'e3b5d47d655b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('breed', table_name='pets')
    op.drop_index('gender', table_name='pets')
    op.drop_index('name', table_name='pets')
    op.drop_index('size', table_name='pets')
    op.drop_table('pets')
    op.add_column('adverts', sa.Column('breed', sa.String(length=80), nullable=True))
    op.add_column('adverts', sa.Column('gender', sa.String(length=80), nullable=True))
    op.add_column('adverts', sa.Column('name', sa.String(length=80), nullable=True))
    op.add_column('adverts', sa.Column('photo', sa.String(length=300), nullable=True))
    op.add_column('adverts', sa.Column('size', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'adverts', ['size'])
    op.create_unique_constraint(None, 'adverts', ['gender'])
    op.create_unique_constraint(None, 'adverts', ['breed'])
    op.create_unique_constraint(None, 'adverts', ['name'])
    op.drop_constraint('adverts_ibfk_1', 'adverts', type_='foreignkey')
    op.drop_column('adverts', 'pet_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adverts', sa.Column('pet_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('adverts_ibfk_1', 'adverts', 'pets', ['pet_id'], ['id'])
    op.drop_constraint(None, 'adverts', type_='unique')
    op.drop_constraint(None, 'adverts', type_='unique')
    op.drop_constraint(None, 'adverts', type_='unique')
    op.drop_constraint(None, 'adverts', type_='unique')
    op.drop_column('adverts', 'size')
    op.drop_column('adverts', 'photo')
    op.drop_column('adverts', 'name')
    op.drop_column('adverts', 'gender')
    op.drop_column('adverts', 'breed')
    op.create_table('pets',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('breed', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('size', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('photo', mysql.VARCHAR(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('size', 'pets', ['size'], unique=True)
    op.create_index('name', 'pets', ['name'], unique=True)
    op.create_index('gender', 'pets', ['gender'], unique=True)
    op.create_index('breed', 'pets', ['breed'], unique=True)
    # ### end Alembic commands ###
