"""empty message

Revision ID: a38abd91ab16
Revises: eb70322f2065
Create Date: 2019-08-19 23:35:12.952702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38abd91ab16'
down_revision = 'eb70322f2065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adverts', sa.Column('photo_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adverts', 'photo_url')
    # ### end Alembic commands ###
