"""empty message

Revision ID: af4097442f1a
Revises: 2167f59d73d4
Create Date: 2019-08-14 17:39:58.855117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4097442f1a'
down_revision = '2167f59d73d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('pet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'photo', 'pets', ['pet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.drop_column('photo', 'pet_id')
    # ### end Alembic commands ###
