"""empty message

Revision ID: b762f56a8109
Revises: d1ccf05d0e51
Create Date: 2019-07-18 19:23:49.158313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b762f56a8109'
down_revision = 'd1ccf05d0e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost', sa.Column('petName', sa.String(length=80), nullable=False))
    op.drop_index('email', table_name='lost')
    op.drop_index('username', table_name='lost')
    op.drop_column('lost', 'email')
    op.drop_column('lost', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost', sa.Column('username', mysql.VARCHAR(length=80), nullable=False))
    op.add_column('lost', sa.Column('email', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('username', 'lost', ['username'], unique=True)
    op.create_index('email', 'lost', ['email'], unique=True)
    op.drop_column('lost', 'petName')
    # ### end Alembic commands ###
