"""empty message

Revision ID: ba209846dae1
Revises: 7df31999d1f2
Create Date: 2019-08-18 01:25:49.021674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba209846dae1'
down_revision = '7df31999d1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adverts', sa.Column('street1', sa.String(length=80), nullable=True))
    op.add_column('adverts', sa.Column('street2', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adverts', 'street2')
    op.drop_column('adverts', 'street1')
    # ### end Alembic commands ###
