"""empty message

Revision ID: d1ccf05d0e51
Revises: 0a73ddfdeedf
Create Date: 2019-07-18 18:07:29.156007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1ccf05d0e51'
down_revision = '0a73ddfdeedf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'findings',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('user', 'searchRequests',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'searchRequests',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user', 'findings',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
