"""empty message

Revision ID: eb70322f2065
Revises: ba209846dae1
Create Date: 2019-08-18 11:47:19.374556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb70322f2065'
down_revision = 'ba209846dae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('firstname', table_name='user')
    op.drop_index('lastname', table_name='user')
    op.drop_index('password', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('password', 'user', ['password'], unique=True)
    op.create_index('lastname', 'user', ['lastname'], unique=True)
    op.create_index('firstname', 'user', ['firstname'], unique=True)
    # ### end Alembic commands ###
