"""empty message

Revision ID: f7819058d5c3
Revises: 4bb2efd86fee
Create Date: 2019-08-11 01:42:07.067621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7819058d5c3'
down_revision = '4bb2efd86fee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('chip_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'chip_num')
    # ### end Alembic commands ###
